name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'  
  push:
    branches: [ yellow_paper ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: nvidia/cuda:12.0.0-devel-ubuntu22.04
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    env:
      DEBIAN_FRONTEND: "noninteractive"
      TZ: "Asia/Singapore"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Apt Requirements
      run: timedatectl set-timezone Asia/Singapore && DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y doxygen sphinx cmake python3-pip libgmp-dev libcjson1 libcjson-dev
    - name: Pip3 Requirements
      run: pip3 install -r docs/requirements.txt
    - name: Configure CMake
      run: cmake -S . -B build -G "Unix Makefiles" -DWITH_DOCS=ON
    - name: Build docs
      run:  cmake --build build --target docs 
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/docs/docs/sphinx # The folder the action should deploy.